backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: homepage
    label: Homepage
    files:
      - file: "src/cms/templates/homepage_de.json"
        name: de
        label: Homepage (de)
        format: json
        fields:
          - {label: Title, name: title, widget: string}


      
