backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: homepage
    label: Homepage
    delete: false
    files:
      - file: "src/cms/templates/homepage.json"
        name: homepage
        label: Homepage
        format: json
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "homepage"}
          - {label: Title, name: title, widget: language-string, hint: "title will be displayed in browser (SEO)"}
          - {label: Meta Description, name: metaDescription, widget: language-string, hint: "invisible; important for SEO"}
          - {label: Message, name: message, widget: language-string}
      - file: "src/cms/templates/homepage.de.json"
        name: homepage-de
        label: Homepage (de)
        format: json
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "homepage"}
          - {label: "Language", name: "language", widget: "hidden", default: "de"}
          - {label: Title, name: title, widget: string, hint: "title will be displayed in browser (SEO)"}
          - {label: Meta Description, name: metaDescription, widget: text, hint: "invisible; important for SEO"}
          - {label: Message, name: message, widget: string}
      - file: "src/cms/templates/homepage.en.json"
        name: homepage-en
        label: Homepage (en)
        format: json
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "homepage"}
          - {label: "Language", name: "language", widget: "hidden", default: "en"}
          - {label: Title, name: title, widget: string, hint: "title will be displayed in browser (SEO)"}
          - {label: Meta Description, name: metaDescription, widget: text, hint: "invisible; important for SEO"}
          - {label: Message, name: message, widget: string}
      - file: "src/cms/templates/homepage.mk.json"
        name: homepage-mk
        label: Homepage (mk)
        format: json
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "homepage"}
          - {label: "Language", name: "language", widget: "hidden", default: "mk"}
          - {label: Title, name: title, widget: string, hint: "title will be displayed in browser (SEO)"}
          - {label: Meta Description, name: metaDescription, widget: text, hint: "invisible; important for SEO"}
          - {label: Message, name: message, widget: string}
      - file: "src/cms/templates/homepage.al.json"
        name: homepage-al
        label: Homepage (al)
        format: json
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "homepage"}
          - {label: "Language", name: "language", widget: "hidden", default: "al"}
          - {label: Title, name: title, widget: string, hint: "title will be displayed in browser (SEO)"}
          - {label: Meta Description, name: metaDescription, widget: text, hint: "invisible; important for SEO"}
          - {label: Message, name: message, widget: string}


      
